# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Diagram',
                'verbose_name_plural': 'Diagrams',
            },
        ),
    ]
