# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-29 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BPMN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_content', models.TextField(max_length=0)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
