# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmndesigner', '0001_initial_diagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='svg_content',
            field=models.TextField(blank=True, null=True, verbose_name='SVG Content'),
        ),
    ]
