# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmndesigner', '0002_diagram_svg_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='svg_content',
            field=models.TextField(default='', verbose_name='SVG Content'),
            preserve_default=False,
        ),
    ]
