# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmndesigner', '0003_auto_20180430_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='content',
            field=models.TextField(verbose_name='XML Content'),
        ),
    ]
