# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmndesigner', '0004_auto_20180430_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='XML Content'),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='svg_content',
            field=models.TextField(blank=True, null=True, verbose_name='SVG Content'),
        ),
    ]
