# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmndesigner', '0005_auto_20180430_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='content',
            field=models.TextField(blank=True, default='<?xml version="1.0" encoding="UTF-8"?>\n<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" id="Definitions_1m53hef" targetNamespace="http://bpmn.io/schema/bpmn">\n  <bpmn:process id="Process_1" isExecutable="false" />\n  <bpmndi:BPMNDiagram id="BPMNDiagram_1">\n    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1" />\n  </bpmndi:BPMNDiagram>\n</bpmn:definitions>\n', null=True, verbose_name='XML Content'),
        ),
    ]
