# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmndesigner', '0006_auto_20180430_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='svg_content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='SVG Content'),
        ),
    ]
